### ISSUE TITLE
`batch_norm` fix in `workflow.yaml` results in error

### ISSUE THREAD

**Issue by Analect** [terrytangyuan/distributed-ml-patterns#5]
@terrytangyuan  ... per the bottom of issue https://github.com/terrytangyuan/distributed-ml-patterns/issues/3, when I try to 'fix' the `workflow.yaml` to specify `--model_type` `batch_norm`, the workflow errors-out each time. I have tried multiple times. It will only run-through if I revert this to `dropout` (but then two of the three models are using `dropout`, which is presumably wrong). I'm including logs from the workflow runs below. Are you experiencing the same with the `batch_norm` fix?

While it works with `kubectl create -n kubeflow -f workflow.yaml`, I notice when trying to use the argo cli to submit the workflow, it fails with this:

```
argo submit workflow.yaml
FATA[2023-08-23T16:09:28.397Z] Failed to parse workflow: json: unknown field "successCondition"
```

This is the section of `workflow.yaml` that has been modified to fix `batch_norm`.
```
# modified `workflow.yaml` with `batch_norm` in #L149
- name: cnn-model-with-batch-norm
    serviceAccountName: training-operator
    resource:
      action: create
      setOwnerReference: true
      successCondition: status.replicaStatuses.Worker.succeeded = 2
      failureCondition: status.replicaStatuses.Worker.failed > 0
      manifest: |
        apiVersion: kubeflow.org/v1
        kind: TFJob
        metadata:
          generateName: multi-worker-training-
        spec:
          runPolicy:
            cleanPodPolicy: None
          tfReplicaSpecs:
            Worker:
              replicas: 2
              restartPolicy: Never
              template:
                spec:
                  containers:
                    - name: tensorflow
                      image: kubeflow/multi-worker-strategy:v0.1
                      imagePullPolicy: IfNotPresent
                      command: ["python", "/multi-worker-distributed-training.py", "--saved_model_dir", "/trained_model/saved_model_versions/3/", "--checkpoint_dir", "/trained_model/checkpoint", "--model_type", "batch_norm"]
                      volumeMounts:
                        - mountPath: /trained_model
                          name: training
                      resources:
                        limits:
                          cpu: 500m
                  volumes:
                    - name: training
                      persistentVolumeClaim:
                        claimName: strategy-volume
```

These are the logs from the two worker nodes that error-out.

```
kubectl logs multi-worker-training-zckqg-worker-0 -n kubeflow
#returns
Dataset fashion_mnist downloaded and prepared to /root/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
Training CNN model with batch normalization
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 32)        320

 batch_normalization (BatchN  (None, 26, 26, 32)       128
 ormalization)

 activation (Activation)     (None, 26, 26, 32)        0

 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496

 batch_normalization_1 (Batc  (None, 11, 11, 64)       256
 hNormalization)

 activation_1 (Activation)   (None, 11, 11, 64)        0

 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0
 2D)

 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928

 flatten (Flatten)           (None, 576)               0

 dense (Dense)               (None, 64)                36928

 dense_1 (Dense)             (None, 10)                650

=================================================================
Total params: 93,706
Trainable params: 93,514
Non-trainable params: 192
_________________________________________________________________
2023-08-23 14:39:29.851994: W tensorflow/core/framework/dataset.cc:769] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
70/70 [==============================] - ETA: 0s - loss: 2.3749 - accuracy: 1.2304
Learning rate for epoch 1 is 0.0010000000474974513
70/70 [==============================] - 32s 307ms/step - loss: 1.1875 - accuracy: 0.6152 - lr: 0.0010
2023-08-23 14:40:16.091245: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2023-08-23 14:40:16.099838: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _update_step_xla while saving (showing 4 of 4). These functions will not be directly callable after loading.
WARNING:tensorflow:From /usr/local/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
WARNING:tensorflow:From /usr/local/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _update_step_xla while saving (showing 4 of 4). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/multi-worker-distributed-training.py", line 234, in <module>
    main(parsed_args)
  File "/multi-worker-distributed-training.py", line 205, in main
    tf.saved_model.save(multi_worker_model, model_path, signatures=signatures)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1231, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1267, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1440, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1395, in _build_meta_graph_impl
    asset_info, exported_graph = _fill_meta_graph_def(
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 793, in _fill_meta_graph_def
    object_map, tensor_map, asset_info = saveable_view.map_resources()
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 400, in map_resources
    tensors = obj._export_to_saved_model_graph(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 2277, in _export_to_saved_model_graph
    raise ValueError(
ValueError: Unable to save function b'__inference_signature_wrapper_146598' for the following reason(s):

ConcreteFunction that uses distributed variables in certain way cannot be saved.
If you're saving with

tf.saved_model.save(..., signatures=f.get_concrete_function())

do

@tf.function(input_signature=...)
def f_with_input_signature():
  ...

tf.saved_model.save(..., signatures=f_with_input_signature)`

instead.
```

```
kubectl logs multi-worker-training-zckqg-worker-1 -n kubeflow
# returns
Dataset fashion_mnist downloaded and prepared to /root/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
Training CNN model with batch normalization
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 32)        320

 batch_normalization (BatchN  (None, 26, 26, 32)       128
 ormalization)

 activation (Activation)     (None, 26, 26, 32)        0

 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496

 batch_normalization_1 (Batc  (None, 11, 11, 64)       256
 hNormalization)

 activation_1 (Activation)   (None, 11, 11, 64)        0

 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0
 2D)

 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928

 flatten (Flatten)           (None, 576)               0

 dense (Dense)               (None, 64)                36928

 dense_1 (Dense)             (None, 10)                650

=================================================================
Total params: 93,706
Trainable params: 93,514
Non-trainable params: 192
_________________________________________________________________
2023-08-23 14:39:29.845471: W tensorflow/core/framework/dataset.cc:769] Input of GeneratorDatasetOp::Dataset will not be optimized because the dataset does not implement the AsGraphDefInternal() method needed to apply optimizations.
70/70 [==============================] - ETA: 0s - loss: 2.3749 - accuracy: 1.2304
Learning rate for epoch 1 is 0.0010000000474974513
70/70 [==============================] - 32s 307ms/step - loss: 1.1875 - accuracy: 0.6152 - lr: 0.0010
2023-08-23 14:40:02.230116: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2023-08-23 14:40:02.236010: W tensorflow/core/kernels/data/cache_dataset_ops.cc:856] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _update_step_xla while saving (showing 4 of 4). These functions will not be directly callable after loading.
WARNING:tensorflow:From /usr/local/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
WARNING:tensorflow:From /usr/local/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py:629: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _update_step_xla while saving (showing 4 of 4). These functions will not be directly callable after loading.
Traceback (most recent call last):
  File "/multi-worker-distributed-training.py", line 234, in <module>
    main(parsed_args)
  File "/multi-worker-distributed-training.py", line 205, in main
    tf.saved_model.save(multi_worker_model, model_path, signatures=signatures)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1231, in save
    save_and_return_nodes(obj, export_dir, signatures, options)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1267, in save_and_return_nodes
    _build_meta_graph(obj, signatures, options, meta_graph_def))
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1440, in _build_meta_graph
    return _build_meta_graph_impl(obj, signatures, options, meta_graph_def)
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 1395, in _build_meta_graph_impl
    asset_info, exported_graph = _fill_meta_graph_def(
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 793, in _fill_meta_graph_def
    object_map, tensor_map, asset_info = saveable_view.map_resources()
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/saved_model/save.py", line 400, in map_resources
    tensors = obj._export_to_saved_model_graph(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/eager/polymorphic_function/monomorphic_function.py", line 2277, in _export_to_saved_model_graph
    raise ValueError(
ValueError: Unable to save function b'__inference_signature_wrapper_146542' for the following reason(s):

ConcreteFunction that uses distributed variables in certain way cannot be saved.
If you're saving with

tf.saved_model.save(..., signatures=f.get_concrete_function())

do

@tf.function(input_signature=...)
def f_with_input_signature():
  ...

tf.saved_model.save(..., signatures=f_with_input_signature)`

instead.
```
